RULES = [
    {'rule_id':'DET-SSH-001','name':'SSH brute force','severity':'high','confidence':0.86,'tactic':'Credential Access','technique':'T1110','field_equals':{'event_type':'ssh_login','status':'failure'},'threshold':5,'time_window_minutes':5,'group_by':['src_ip'],'evidence_fields':['asset','user','src_ip','message']},
    {'rule_id':'DET-SSH-002','name':'Successful login after multiple failures','severity':'high','confidence':0.84,'tactic':'Initial Access','technique':'T1078','field_equals':{'event_type':'ssh_login','status':'success'},'threshold':4,'time_window_minutes':10,'group_by':['src_ip','user'],'evidence_fields':['asset','user','src_ip','message']},
    {'rule_id':'DET-PS-001','name':'Encoded PowerShell command execution','severity':'critical','confidence':0.9,'tactic':'Execution','technique':'T1059.001','field_equals':{'event_type':'powershell_execution'},'contains':{'command_line':['-enc','encodedcommand','frombase64string','bypass','hidden']},'threshold':1,'time_window_minutes':1,'group_by':['asset','user'],'evidence_fields':['asset','user','process_name','command_line']},
    {'rule_id':'DET-NET-001','name':'Internal port scan','severity':'medium','confidence':0.78,'tactic':'Discovery','technique':'T1046','field_equals':{'event_type':'network_connection'},'threshold':8,'time_window_minutes':5,'group_by':['src_ip'],'distinct_field':'dst_ip','evidence_fields':['src_ip','dst_ip','message']},
    {'rule_id':'DET-WIN-001','name':'New admin account creation','severity':'critical','confidence':0.88,'tactic':'Persistence','technique':'T1136','field_equals':{'event_type':'admin_account_change'},'contains':{'message':['admin','administrator','domain admins','created','added']},'threshold':1,'time_window_minutes':1,'group_by':['asset','user'],'evidence_fields':['asset','user','message']},
    {'rule_id':'DET-WAF-001','name':'SQL injection attempt','severity':'high','confidence':0.82,'tactic':'Initial Access','technique':'T1190','field_equals':{'event_type':'http_request'},'regex':{'message':['(?i)union\\s+select','(?i)or\\s+1=1','(?i)information_schema','(?i)sqlmap','(?i)../']},'threshold':1,'time_window_minutes':1,'group_by':['src_ip'],'evidence_fields':['src_ip','message']},
    {'rule_id':'DET-AI-001','name':'Rare source IP for user','severity':'medium','confidence':0.7,'tactic':'Initial Access','technique':'T1078','field_equals':{'event_type':'ssh_login','status':'success'},'threshold':1,'time_window_minutes':1,'group_by':['user','src_ip'],'evidence_fields':['user','src_ip','asset']},
    {'rule_id':'DET-AI-002','name':'Off-hours privileged activity','severity':'medium','confidence':0.74,'tactic':'Privilege Escalation','technique':'T1078','field_equals':{'event_type':'ssh_login','status':'success'},'threshold':1,'time_window_minutes':1,'group_by':['user','asset'],'evidence_fields':['user','asset','src_ip','message']},
]
