from .rule_validation import validate_rules


RULES = validate_rules([
 {'rule_id':'DET-SSH-001','name':'SSH brute force','severity':'high','confidence':0.86,'tactic':'Credential Access','technique':'T1110','field_equals':{'event_type':'ssh_login','status':'failure'},'threshold':5,'time_window_minutes':5,'group_by':['src_ip']},
 {'rule_id':'DET-SSH-002','name':'Successful login after multiple failures','severity':'high','confidence':0.84,'tactic':'Initial Access','technique':'T1078','field_equals':{'event_type':'ssh_login','status':'success'},'threshold':4,'time_window_minutes':10,'group_by':['src_ip','user']},
 {'rule_id':'DET-SSH-003','name':'SSH password spraying across users','severity':'high','confidence':0.83,'tactic':'Credential Access','technique':'T1110.003','field_equals':{'event_type':'ssh_login','status':'failure'},'threshold':5,'time_window_minutes':10,'group_by':['src_ip'],'distinct_field':'user'},
 {'rule_id':'DET-PS-001','name':'Encoded PowerShell execution','severity':'critical','confidence':0.9,'tactic':'Execution','technique':'T1059.001','field_equals':{'event_type':'powershell_execution'},'contains':{'command_line':['-enc','encodedcommand','frombase64string','bypass','hidden']}},
 {'rule_id':'DET-NET-001','name':'Internal port scan','severity':'medium','confidence':0.78,'tactic':'Discovery','technique':'T1046','field_equals':{'event_type':'network_connection'},'threshold':8,'time_window_minutes':5,'group_by':['src_ip'],'distinct_field':'dst_ip'},
 {'rule_id':'DET-WIN-001','name':'New admin account creation','severity':'critical','confidence':0.88,'tactic':'Persistence','technique':'T1136','field_equals':{'event_type':'admin_account_change'},'contains':{'message':['admin','administrator','created','added']}},
 {'rule_id':'DET-WIN-002','name':'LSASS credential dumping via ProcDump or comsvcs','severity':'critical','confidence':0.94,'tactic':'Credential Access','technique':'T1003.001','field_equals':{'source':'windows','event_type':'windows_event'},'regex':{'command_line':['(?i)\\bprocdump(?:64)?(?:\\.exe)?\\b.*(?:-ma\\s+)?lsass(?:\\.exe)?\\b','(?i)\\brundll32(?:\\.exe)?\\b.*\\bcomsvcs\\.dll\\b.*\\bMiniDump\\b.*\\blsass(?:\\.exe)?\\b']}},
 {'rule_id':'DET-WIN-003','name':'Remote payload transfer via Certutil','severity':'high','confidence':0.9,'tactic':'Command and Control','technique':'T1105','field_equals':{'source':'windows','event_type':'windows_event'},'regex':{'command_line':['(?i)\\bcertutil(?:\\.exe)?\\b.*(?:-urlcache|-verifyctl).*https?://']}},
 {'rule_id':'DET-WIN-004','name':'Windows event log clearing via Wevtutil','severity':'high','confidence':0.93,'tactic':'Defense Evasion','technique':'T1070.001','field_equals':{'source':'windows','event_type':'windows_event'},'regex':{'command_line':['(?i)\\bwevtutil(?:\\.exe)?\\b\\s+(?:cl|clear-log)\\s+\\S+']}},
 {'rule_id':'DET-WIN-005','name':'Remote script execution via Mshta','severity':'high','confidence':0.92,'tactic':'Defense Evasion','technique':'T1218.005','field_equals':{'source':'windows','event_type':'windows_event'},'regex':{'command_line':['(?i)\\bmshta(?:\\.exe)?\\b[^\\r\\n]*(?:https?|javascript|vbscript):']}},
 {'rule_id':'DET-WIN-006','name':'Remote scriptlet execution via Regsvr32','severity':'high','confidence':0.94,'tactic':'Defense Evasion','technique':'T1218.010','field_equals':{'source':'windows','event_type':'windows_event'},'regex':{'command_line':['(?i)\\bregsvr32(?:\\.exe)?\\b(?=[^\\r\\n]*\\bscrobj\\.dll\\b)(?=[^\\r\\n]*/i:\\s*"?https?://)[^\\r\\n]*']}},
 {'rule_id':'DET-WIN-007','name':'Remote process creation via WMIC','severity':'high','confidence':0.92,'tactic':'Execution','technique':'T1047','field_equals':{'source':'windows','event_type':'windows_event'},'regex':{'command_line':['(?i)\\bwmic(?:\\.exe)?\\b(?=[^\\r\\n]*/node:\\s*"?(?!localhost\\b|127\\.0\\.0\\.1\\b|::1\\b)[^\\s"]+"?)(?=[^\\r\\n]*\\bprocess\\s+call\\s+create\\b)[^\\r\\n]*']}},
 {'rule_id':'DET-WIN-008','name':'Script proxy execution via Rundll32','severity':'high','confidence':0.94,'tactic':'Defense Evasion','technique':'T1218.011','field_equals':{'source':'windows','event_type':'windows_event'},'regex':{'command_line':['(?i)\\brundll32(?:\\.exe)?\\b(?=[^\\r\\n]*\\bjavascript\\s*:)(?=[^\\r\\n]*\\bmshtml\\s*,\\s*RunHTMLApplication\\b)[^\\r\\n]*']}},
 {'rule_id':'DET-WAF-001','name':'SQL injection attempt','severity':'high','confidence':0.82,'tactic':'Initial Access','technique':'T1190','field_equals':{'event_type':'http_request'},'regex':{'message':['(?i)union\\s+select','(?i)or\\s+1=1','(?i)sqlmap','(?i)information_schema','(?i)../']}},
])
