parser: cloudtrail
format: json
fields: eventTime, eventName, userIdentity, sourceIPAddress, awsRegion
normalization: cloud_event
mapped_fields:
  sourceIPAddress: source.ip
  eventName: event.action
  userIdentity.arn: user.id
